spring:
  profiles:
    active: green_server
    group:
      local_server: local, common, secret
      blue_server: blue, common, secret
      green_server: green, common, secret

server:
  env: green
---

spring:
  config:
    activate:
      on-profile: local



server:
  port: 8080
  deploy-address: localhost
  name: local
---

spring:
  config:
    activate:
      on-profile: blue



server:
  port: 8080
  deploy-address: 13.125.104.0
  name: blue_server
---

spring:
  config:
    activate:
      on-profile: green



server:
  port: 9090
  deploy-address: 13.125.104.0
  name: green_server
---

spring:
  config:
    activate:
      on-profile: common
client:
  deploy-address: "localhost:3000"

